eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
server:
  port: 8006
spring:
  application:
    name: api-rabbitmq
logging:
    level:
      com.cloud.platform.admin.dao: DEBUG