eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
server:
  port: 8085
  servlet:
    context-path: /question
spring:
  application:
    name: api-oauth
  security:
    user:
      name: codesheep
      password: 123456
  datasource:
    url: jdbc:mysql://localhost:3306/question?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: mapper/**Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml
logging:
    level:
      com.question.admin.dao: DEBUG