server:
  port: 8001
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 30000